# language: pt
#encoding iso-8859-1

@Testar
Funcionalidade:  GET - Buscar usuário para autenticação

Cenário: Validar Consultar Lista de Usuários Sucesso
	Quando consulto a lista de usuários
	Então verifico status code 200
	E verifico que há uma lista no body "users"
	E verifico no body "$" que há o campo "users"
	E verifico no body "users[0]" que há o campo "id"
	E verifico que o valor do campo "users[0].id" é 1
	E verifico no body "users[0]" que há o campo "firstName"
	E verifico que o valor do campo "users[0].firstName" é "Terry"
	E verifico no body "users[0]" que há o campo "lastName"
	E verifico que o valor do campo "users[0].lastName" é "Medhurst"
	E verifico no body "users[0]" que há o campo "maidenName"
	E verifico que o valor do campo "users[0].maidenName" é "Smitham"
	E verifico no body "users[0]" que há o campo "age"
	E verifico que o valor do campo "users[0].age" é 50
	E verifico no body "users[0]" que há o campo "gender"
	E verifico que o valor do campo "users[0].gender" é "male"
	E verifico no body "users[0]" que há o campo "email"
	E verifico que o valor do campo "users[0].email" é "atuny0@sohu.com"
	E verifico no body "users[0]" que há o campo "phone"
	E verifico que o valor do campo "users[0].phone" é "+63 791 675 8914"
	E verifico no body "users[0]" que há o campo "username"
	E verifico que o valor do campo "users[0].username" é "atuny0"
	E verifico no body "users[0]" que há o campo "password"
	E verifico que o valor do campo "users[0].password" é "9uQFF1Lh"
	E verifico no body "users[0]" que há o campo "birthDate"
	E verifico que o valor do campo "users[0].birthDate" é "2000-12-25"
	E verifico no body "users[0]" que há o campo "image"
	E verifico que o valor do campo "users[0].image" é "https://robohash.org/hicveldicta.png"
	E verifico no body "users[0]" que há o campo "bloodGroup"
	E verifico que o valor do campo "users[0].bloodGroup" é "A−"
	E verifico no body "users[0]" que há o campo "height"
	E verifico que o valor do campo "users[0].height" é 189
	E verifico no body "users[0]" que há o campo "weight"
	E verifico que o valor do campo "users[0].weight" é 75,4
	E verifico no body "users[0]" que há o campo "eyeColor"
	E verifico que o valor do campo "users[0].eyeColor" é "Green"
	E verifico no body "users[0]" que há o campo "hair"
	E verifico no body "users[0].hair" que há o campo "color"
	E verifico que o valor do campo "users[0].hair.color" é "Black"
	E verifico no body "users[0].hair" que há o campo "type"
	E verifico que o valor do campo "users[0].hair.type" é "Strands"
	E verifico no body "users[0]" que há o campo "domain"
	E verifico que o valor do campo "users[0].domain" é "slashdot.org"
	E verifico no body "users[0]" que há o campo "ip"
	E verifico que o valor do campo "users[0].ip" é "117.29.86.254"
	E verifico no body "users[0]" que há o campo "address"
	E verifico no body "users[0].address" que há o campo "address"
	E verifico que o valor do campo "users[0].address.address" é "1745 T Street Southeast"
	E verifico no body "users[0].address" que há o campo "city"
	E verifico que o valor do campo "users[0].address.city" é "Washington"
	E verifico no body "users[0].address" que há o campo "coordinates"
	E verifico no body "users[0].address.coordinates" que há o campo "lat"
	E verifico que o valor do campo "users[0].address.coordinates.lat" é 38,867033
	E verifico no body "users[0].address.coordinates" que há o campo "lng"
	E verifico que o valor do campo "users[0].address.coordinates.lng" é -76,979235
	E verifico no body "users[0].address" que há o campo "postalCode"
	E verifico que o valor do campo "users[0].address.postalCode" é "20020"
	E verifico no body "users[0].address" que há o campo "state"
	E verifico que o valor do campo "users[0].address.state" é "DC"
	E verifico no body "users[0]" que há o campo "macAddress"
	E verifico que o valor do campo "users[0].macAddress" é "13:69:BA:56:A3:74"
	E verifico no body "users[0]" que há o campo "university"
	E verifico que o valor do campo "users[0].university" é "Capitol University"
	E verifico no body "users[0]" que há o campo "bank"
	E verifico no body "users[0].bank" que há o campo "cardExpire"
	E verifico que o valor do campo "users[0].bank.cardExpire" é "06/22"
	E verifico no body "users[0].bank" que há o campo "cardNumber"
	E verifico que o valor do campo "users[0].bank.cardNumber" é "50380955204220685"
	E verifico no body "users[0].bank" que há o campo "cardType"
	E verifico que o valor do campo "users[0].bank.cardType" é "maestro"
	E verifico no body "users[0].bank" que há o campo "currency"
	E verifico que o valor do campo "users[0].bank.currency" é "Peso"
	E verifico no body "users[0].bank" que há o campo "iban"
	E verifico que o valor do campo "users[0].bank.iban" é "NO17 0695 2754 967"
	E verifico no body "users[0]" que há o campo "company"
	E verifico no body "users[0].company" que há o campo "address"
	E verifico no body "users[0].company.address" que há o campo "address"
	E verifico que o valor do campo "users[0].company.address.address" é "629 Debbie Drive"
	E verifico no body "users[0].company.address" que há o campo "city"
	E verifico que o valor do campo "users[0].company.address.city" é "Nashville"
	E verifico no body "users[0].company.address" que há o campo "coordinates"
	E verifico no body "users[0].company.address.coordinates" que há o campo "lat"
	E verifico que o valor do campo "users[0].company.address.coordinates.lat" é 36,208114
	E verifico no body "users[0].company.address.coordinates" que há o campo "lng"
	E verifico que o valor do campo "users[0].company.address.coordinates.lng" é -86,58621199999999
	E verifico no body "users[0].company.address" que há o campo "postalCode"
	E verifico que o valor do campo "users[0].company.address.postalCode" é "37076"
	E verifico no body "users[0].company.address" que há o campo "state"
	E verifico que o valor do campo "users[0].company.address.state" é "TN"
	E verifico no body "users[0].company" que há o campo "department"
	E verifico que o valor do campo "users[0].company.department" é "Marketing"
	E verifico no body "users[0].company" que há o campo "name"
	E verifico que o valor do campo "users[0].company.name" é "Blanda-O'Keefe"
	E verifico no body "users[0].company" que há o campo "title"
	E verifico que o valor do campo "users[0].company.title" é "Help Desk Operator"
	E verifico no body "users[0]" que há o campo "ein"
	E verifico que o valor do campo "users[0].ein" é "20-9487066"
	E verifico no body "users[0]" que há o campo "ssn"
	E verifico que o valor do campo "users[0].ssn" é "661-64-2976"
	E verifico no body "users[0]" que há o campo "userAgent"
	E verifico que o valor do campo "users[0].userAgent" é "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/12.0.702.0 Safari/534.24"
